/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class zb_zxy_zyc_klotski_Game */

#ifndef _Included_zb_zxy_zyc_klotski_Game
#define _Included_zb_zxy_zyc_klotski_Game

#ifdef __cplusplus
extern "C" {
#endif

#define		result_ok = 0;
#define		result_ng = -1;

/*
 * Class:     zb_zxy_zyc_klotski_Game
 * Method:    getStartBoards
 * Signature: ()[Lzb/zxy/zyc/klotski/Board;
 */
JNIEXPORT jobjectArray JNICALL Java_zb_zxy_zyc_klotski_Game_getStartBoards
  (JNIEnv *, jobject);

/*
 * Class:     zb_zxy_zyc_klotski_Game
 * Method:    start
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_zb_zxy_zyc_klotski_Game_start
  (JNIEnv *, jobject);

/*
 * Class:     zb_zxy_zyc_klotski_Game
 * Method:    end
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_zb_zxy_zyc_klotski_Game_end
  (JNIEnv *, jobject);

/*
 * Class:     zb_zxy_zyc_klotski_Game
 * Method:    doanalysis
 * Signature: (Lzb/zxy/zyc/klotski/Board;)I
 */
JNIEXPORT jint JNICALL Java_zb_zxy_zyc_klotski_Game_doAnalysis
  (JNIEnv *, jobject, jobject);

/*
 * Class:     zb_zxy_zyc_klotski_Game
 * Method:    getNextBoard
 * Signature: (Lzb/zxy/zyc/klotski/Board;)Lzb/zxy/zyc/klotski/Board;
 */
JNIEXPORT jobject JNICALL Java_zb_zxy_zyc_klotski_Game_getNextBoard
  (JNIEnv *, jobject, jobject);

/*
 * Class:     zb_zxy_zyc_klotski_Game
 * Method:    printBoard
 * Signature: (Lzb/zxy/zyc/klotski/Board;)V
 */
JNIEXPORT void JNICALL Java_zb_zxy_zyc_klotski_Game_printBoard
  (JNIEnv *, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
